theme: minima
title: test-title
author: test-user
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  test-descritpion
  
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
